amp_opt_level: 1
assume_yes: false
base_lr: 0.005
batch_size: 32
checkpoint: null
config: config/train.yaml
debug: false
device: 0
eval_interval: 1
eval_start: 1
feeder: feeders.feeder.Feeder
forward_batch_size: 16
half: false
ignore_weights: []
k_num: 5
log_interval: 100
model: model.msg3d.Model
model_args:
  graph: graph.ntu_rgb_d.AdjMatrixGraph
  num_class: 1
  num_g3d_scales: 6
  num_gcn_scales: 13
  num_person: 2
  num_point: 25
model_saved_name: ''
modify_weights: null
nesterov: true
num_epoch: 50
num_worker: 48
optimizer: SGD
optimizer_states: null
phase: train
print_log: true
save_interval: 1
save_score: false
seed: 146
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 40
test_batch_size: 32
test_feeder_args:
  data_path: /mnt/data2/MS-G3D/test
  label_path: null
train_feeder_args:
  data_path: /mnt/data2/MS-G3D/train
  debug: false
  label_path: null
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
weight_decay: 0.0005
weights: null
work_dir: model/
